name: black-action
on: [pull_request]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1.1.11
        id: action_black
        with:
          black_args: "--line-length 120"
      - name: Push Changes
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          git config --global user.name 'BlackBot'
          git config --global user.email 'bodcsoft@bodc.ac.uk'
          git commit -am "Apply Black formatting to Python code."
          git push
