name: black-action
on: [pull_request]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1.1.11
        id: action_black
        with:
          black_args: "."

      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          git config --global user.name "BlackBot"
          git config --global author.name "BlackBot"
          git config --global user.email "bodcsoft@bodc.ac.uk"
          git config --global author.email "bodcsoft@bodc.ac.uk"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git pull
          git commit -am "Apply Black formatting to Python code."
          git push